### PR TITLE
ClassCastException if Run is WorkflowRun instead of AbstractBuild

### PR DESCRIPTION
**Pull request by escoem**
The listener fails if the build is a WorkflowRun instead of AbstractBuild

### CODE REVIEW

**Comment by buep** [comment]
My colleague will have a look in the new year: https://github.com/Praqma/config-rotator-plugin/issues/12

**Comment by buep** [comment]
Thanks for the PR :-)

**Comment by escoem** [comment]
Thanks to you @buep I will try to send another one making the plugin compatible with pipeline

**Comment by praqma-thi** [comment]
Hey @escoem,

Thanks for the pull request. For further contributions, I'd urge you to contribute to [Praqma/config-rotator-plugin](https://github.com/Praqma/config-rotator-plugin) instead. That's where our active development takes place, we really only push to this repo for releases. Due to an oversight on our end, however, this repository is actually lagging behind a release. :sweat_smile: 

I went ahead and merged your changes into the master there, so we'll be closing this PR soon.
I'll also see to it that the latest release makes it to this repository.

Have a good one,
Thierry

**Comment by escoem** [comment]
I will do _I'd urge you to contribute to Praqma/config-rotator-plugin instead_ next time @praqma-thi :-)

**Pull request merged**
